### ISSUE TITLE
Supicious driver dependencies

### ISSUE THREAD

**Issue by minimeee** [flathub/com.github.Matoking.protontricks#36]
When installing `protontricks` on Ubuntu 22.04, flatpak also installs these two `nvidia` runtimes (the version apparently matches the system driver version):

```
1. [✓] org.freedesktop.Platform.GL.nvidia-520-56-06               1.4                i              flathub            407,5 MB / 407,0 MB
2. [✓] org.freedesktop.Platform.GL32.nvidia-520-56-06             1.4                i              flathub            407,4 MB / 406,9 MB
3. [✓] com.github.Matoking.protontricks                           stable             i              flathub             19,2 MB / 17,0 MB
```

I wonder if and why they `protontricks` actually requires those driver packages?

This may seem like a superfluous question, but those two runtimes are using up over 800MB disk space, which is quite a lot compared to the 17MB size of `protontricks`. This is even more important on a limited system like the Steam Deck.

**Comment by Matoking** [comment]
Protontricks requires support for graphics acceleration, since many Windows applications and games are likely to require it; anything that runs on Proton through Steam should also work using Protontricks, ideally. That graphics driver is part of the Freedesktop runtime and the driver is shared with other Flatpak applications, so you should only need to install it once.

Another option would be to use a non-Flatpak option such as the Protontricks package on AUR, but that is a less convenient option on Steam Deck due to the OS' immutable design.

**Comment by minimeee** [comment]
> anything that runs on Proton through Steam should also work using Protontricks, ideally.

Does that mean that `protontricks` executes windows programs that potentially require hardware acceleration? What are we talking about? Installers for .NET runtimes and similar? Do they really need hardware acceleration? Sorry to bother you, just trying to improve my understanding...

**Comment by Matoking** [comment]
> > anything that runs on Proton through Steam should also work using Protontricks, ideally.
> 
> Does that mean that `protontricks` executes windows programs that potentially require hardware acceleration? What are we talking about? Installers for .NET runtimes and similar? Do they really need hardware acceleration? Sorry to bother you, just trying to improve my understanding...

Protontricks allows to do things besides running Winetricks commands. Using mod managers and launching games through said mod managers is one example.

**Comment by minimeee** [comment]
Thanks for the explanation :+1:
